export const models = [
	//   "gpt-3.5-turbo",
	//   "gpt-3.5-turbo-0301",
	'text-davinci-003',
	'babbage',
	'davinci',
	'text-davinci-001',
	'ada',
	'curie-instruct-beta',
	'code-cushman-001',
	'text-ada-001',
	'text-curie-001',
	'davinci-instruct-beta',
	'text-davinci-002',
	'text-babbage-001',
	'code-davinci-002',
	'curie',
];
